# Testing on headless CI systems
# http://electron.atom.io/docs/tutorial/testing-on-headless-ci/

language: node_js
node_js:
  - "6.1.0"

addons:
  apt:
    packages:
      - xvfb

install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
